/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hdq' at '17-6-21 下午7:09' with Gradle 2.11
 *
 * @author hdq, @date 17-6-21 下午7:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
